type IConstant = {
	[key: string]: any;
};
export const CONSTANT: IConstant = {
	API_END_POINT: "https://fsg-tss.onrender.com/users",
	PER_PAGE_LIMIT_DEFAULT: 100,
	PAGE_DEFAULT: 1,
	TIMEOUT_DEFAULT: 1000000,
	STORAGES_FOLDER: "storages",
	JSON_DATA_FILE: "../storages/data.json",
	HIDDEN_COLUMNS_DEFAULT: {
		firstName: false,
		lastName: false,
		age: false,
		email: false,
		phoneNumber: false,
		address: false,
		city: false,
		state: false,
		zipCode: false,
		jobTitle: false,
		company: false,
		website: false,
		username: false,
		password: false,
		creditCardNumber: false,
		creditCardIssuer: false,
		expirationDate: false,
		cvv: false,
		bankAccountNumber: false,
		routingNumber: false,
		favoriteColor: true,
		favoriteFood: true,
		favoriteMovie: true,
		favoriteBook: true,
		favoriteSong: true,
		favoriteSport: true,
		favoriteAnimal: true,
		favoriteQuote: true,
		aboutMe: true,
		hobbies: true,
	},
};
